[package]
name = "flow-core"
version = "1.2.0"
authors = ["Scott Henning <shenning@cisco.com>", "Tomas Rigaux <trigaux@cisco.com>"]
edition = "20"

[dependencies]
json = { git = "https://github.com/nlohmann/json.git" }
thread_pool = { git = "https://github.com/bshoshany/thread-pool.git" }
